version: "3"
services:
  test-web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    container_name: test-web
    restart: unless-stopped
