version: "3"
services:
  npm:
    image: jc21/nginx-proxy-manager:2.12.4
    ports:
      - "80:80"
      - "81:81" # admin UI
      - "443:443"
    volumes:
    - /srv/data/npm:/data
    - /srv/data/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  test-web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    container_name: test-web
    restart: unless-stopped
